version: "3.7"

services:
 db:
  image: mysql:5.7
  container_name: "lavanga_db"
  expose:
   - "3306"
  networks:
   - backend
  volumes:
   - ../db:/docker-entrypoint-initdb.d
   - sqldb:/var/lib/mysql
   - ../mysql_config/:/etc/mysql/mysql.conf.d/
  environment:
   MYSQL_ROOT_PASSWORD: catty
   
 webapp:
  container_name: "lavanga_app" 
  image: project_webapp #Use image produced by the dockerfile as long as no changes are made to the source
  #build: . #Build from source again. in case of changes to source code
  expose:
   - "8080"
  networks:
   - backend
   - frontend
  volumes:
   - ./static_files:/static_files
   - ./entrypoint.sh:/entrypoint.sh
  environment:
   DB_DIALECT: MYSQL
   DB_URL: jdbc:mysql://lavanga_db:3306/lavagna?useUnicode=true&characterEncoding=utf-8&useSSL=false
   DB_USER: root
   DB_PASS: 
   SPRING_PROFILE: prod

 webserver:
  container_name: "lavagna_webserver"
  build:
   context: .
   dockerfile: Dockerfile.nginx
  ports:
   - "80:8080"
  volumes:
   - ./src/main/webapp:/usr/share/nginx/html
   - ./nginx.conf:/etc/nginx/nginx.conf
  networks:
   - frontend
  
 docker-server:
  container_name: "docs_serv"
  build:
   context: ../doc_server/
   dockerfile: Dockerfile.dockServ
  expose:
   - "8081"
  volumes:
   - ../doc_server/documenation/help:/usr/share/nginx/html
  networks:
   - frontend

networks:
 backend:
  name: backend
  driver: bridge
 frontend:
  name: frontend
  driver: bridge

volumes:
 sqldb:
  external: false
